#
# Copyright 2015 VMware, Inc.  All rights reserved.
# SPDX-License-Identifier: Apache-2.0 OR GPL-3.0-only
#
---
- name: Create a task from template to destroy an IB PSC
  template: src=ib_psc_destroy.yml.j2 dest={{ vcsa_task_directory }}/destroy_appliance.yml
  tags:
    - create_ib_psc_cleanup_task

- name: Create a task from template to destroy an OOB PSC
  template: src=oob_psc_destroy.yml.j2 dest={{ vcsa_task_directory }}/destroy_appliance.yml
  tags:
    - create_oob_psc_cleanup_task

- name: Create a task from template to destroy an IB vCenter
  template: src=ib_vcenter_destroy.yml.j2 dest={{ vcsa_task_directory }}/destroy_appliance.yml
  tags:
    - create_ib_vcenter_cleanup_task

- name: Create a task from template to destroy an OOB vCenter
  template: src=oob_vcenter_destroy.yml.j2 dest={{ vcsa_task_directory }}/destroy_appliance.yml
  tags:
    - create_oob_vcenter_cleanup_task

- name: Create a task from template to destroy an IB vCenter with embedded PSC
  template: src=ib_vcenterpsc_destroy.yml.j2 dest={{ vcsa_task_directory }}/destroy_appliance.yml
  tags:
    - create_ib_vcenterpsc_cleanup_task

- name: Create a task from template to destroy an OOB vCenter with embedded PSC
  template: src=oob_vcenterpsc_destroy.yml.j2 dest={{ vcsa_task_directory }}/destroy_appliance.yml
  tags:
    - create_oob_vcenterpsc_cleanup_task

- name: Destroy the appliance
  include: destroy_appliance.yml
  tags:
    - destroy_appliance
