#
# Copyright 2015 VMware, Inc.  All rights reserved.
# SPDX-License-Identifier: Apache-2.0 OR GPL-3.0-only
#
---
- include: prereqs.yml
- include: deploy.yml
- include: destroy.yml
- include: cleanup.yml
